"""Adding username information to praw_keys

Revision ID: 022d8114fe2a
Revises: 2957ac0e11b6
Create Date: 2016-07-23 12:31:14.863110

"""

# revision identifiers, used by Alembic.
revision = '022d8114fe2a'
down_revision = '2957ac0e11b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praw_keys', sa.Column('authorized_user_id', sa.String(length=256), nullable=True))
    op.add_column('praw_keys', sa.Column('authorized_username', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_praw_keys_authorized_user_id'), 'praw_keys', ['authorized_user_id'], unique=False)
    op.create_index(op.f('ix_praw_keys_authorized_username'), 'praw_keys', ['authorized_username'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_praw_keys_authorized_username'), table_name='praw_keys')
    op.drop_index(op.f('ix_praw_keys_authorized_user_id'), table_name='praw_keys')
    op.drop_column('praw_keys', 'authorized_username')
    op.drop_column('praw_keys', 'authorized_user_id')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praw_keys', sa.Column('authorized_user_id', sa.String(length=256), nullable=True))
    op.add_column('praw_keys', sa.Column('authorized_username', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_praw_keys_authorized_user_id'), 'praw_keys', ['authorized_user_id'], unique=False)
    op.create_index(op.f('ix_praw_keys_authorized_username'), 'praw_keys', ['authorized_username'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_praw_keys_authorized_username'), table_name='praw_keys')
    op.drop_index(op.f('ix_praw_keys_authorized_user_id'), table_name='praw_keys')
    op.drop_column('praw_keys', 'authorized_username')
    op.drop_column('praw_keys', 'authorized_user_id')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('praw_keys', sa.Column('authorized_user_id', sa.String(length=256), nullable=True))
    op.add_column('praw_keys', sa.Column('authorized_username', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_praw_keys_authorized_user_id'), 'praw_keys', ['authorized_user_id'], unique=False)
    op.create_index(op.f('ix_praw_keys_authorized_username'), 'praw_keys', ['authorized_username'], unique=False)
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_praw_keys_authorized_username'), table_name='praw_keys')
    op.drop_index(op.f('ix_praw_keys_authorized_user_id'), table_name='praw_keys')
    op.drop_column('praw_keys', 'authorized_username')
    op.drop_column('praw_keys', 'authorized_user_id')
    ### end Alembic commands ###

