"""index on twitterstatus created at

Revision ID: 0dbd786dc2b3
Revises: dd20ee8bb3d3
Create Date: 2018-09-11 12:32:35.567811

"""

# revision identifiers, used by Alembic.
revision = '0dbd786dc2b3'
down_revision = 'dd20ee8bb3d3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_created_at'), 'twitter_statuses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_created_at'), table_name='twitter_statuses')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_created_at'), 'twitter_statuses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_created_at'), table_name='twitter_statuses')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_created_at'), 'twitter_statuses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_created_at'), table_name='twitter_statuses')
    # ### end Alembic commands ###

