"""add unshortened

Revision ID: 17b20129fb86
Revises: aee0147bf065
Create Date: 2019-03-28 14:30:03.715590

"""

# revision identifiers, used by Alembic.
revision = '17b20129fb86'
down_revision = 'aee0147bf065'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_unshortened_urls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_url', mysql.TEXT(), nullable=True),
    sa.Column('unshortened_url', mysql.TEXT(), nullable=True),
    sa.Column('error_unshortening', mysql.TINYTEXT(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_unshortened_urls_record_created_at'), 'twitter_unshortened_urls', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_unshortened_urls_record_created_at'), table_name='twitter_unshortened_urls')
    op.drop_table('twitter_unshortened_urls')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_unshortened_urls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_url', mysql.TEXT(), nullable=True),
    sa.Column('unshortened_url', mysql.TEXT(), nullable=True),
    sa.Column('error_unshortening', mysql.TINYTEXT(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_unshortened_urls_record_created_at'), 'twitter_unshortened_urls', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_unshortened_urls_record_created_at'), table_name='twitter_unshortened_urls')
    op.drop_table('twitter_unshortened_urls')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_unshortened_urls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('short_url', mysql.TEXT(), nullable=True),
    sa.Column('unshortened_url', mysql.TEXT(), nullable=True),
    sa.Column('error_unshortening', mysql.TINYTEXT(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_unshortened_urls_record_created_at'), 'twitter_unshortened_urls', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_unshortened_urls_record_created_at'), table_name='twitter_unshortened_urls')
    op.drop_table('twitter_unshortened_urls')
    # ### end Alembic commands ###

