"""change subreddit, page ids to varchars

Revision ID: 19759e486129
Revises: 16b25d7cb03c
Create Date: 2016-06-09 18:57:55.092244

"""

# revision identifiers, used by Alembic.
revision = '19759e486129'
down_revision = '16b25d7cb03c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('page_type', sa.Integer(), nullable=True),
    sa.Column('page_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subreddit_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('page_type', sa.Integer(), nullable=True),
    sa.Column('page_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('post_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('subreddit_page')
    op.drop_table('front_page')
    ### end Alembic commands ###


def upgrade_test():
    pass


def downgrade_test():
    pass


def upgrade_production():
    pass


def downgrade_production():
    pass

