"""add lumen tables

Revision ID: 200471c7e77d
Revises: d38d75af1294
Create Date: 2018-06-18 11:28:29.753031

"""

# revision identifiers, used by Alembic.
revision = '200471c7e77d'
down_revision = 'd38d75af1294'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lumen_notice_twitter_user_created_at_index', table_name='lumen_notice_to_twitter_user')
    op.drop_index('ix_lumen_notices_created_at_index', table_name='lumen_notices')
    op.drop_index('ix_twitter_statuses_created_at_index', table_name='twitter_statuses')
    op.drop_index('ix_twitter_users_created_at_index', table_name='twitter_users')
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_twitter_users_created_at_index', 'twitter_users', ['record_created_at'], unique=False)
    op.create_index('ix_twitter_statuses_created_at_index', 'twitter_statuses', ['record_created_at'], unique=False)
    op.create_index('ix_lumen_notices_created_at_index', 'lumen_notices', ['record_created_at'], unique=False)
    op.create_index('ix_lumen_notice_twitter_user_created_at_index', 'lumen_notice_to_twitter_user', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lumen_notice_twitter_user_created_at_index', table_name='lumen_notice_to_twitter_user')
    op.drop_index('ix_lumen_notices_created_at_index', table_name='lumen_notices')
    op.drop_index('ix_twitter_statuses_created_at_index', table_name='twitter_statuses')
    op.drop_index('ix_twitter_users_created_at_index', table_name='twitter_users')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_twitter_users_created_at_index', 'twitter_users', ['record_created_at'], unique=False)
    op.create_index('ix_twitter_statuses_created_at_index', 'twitter_statuses', ['record_created_at'], unique=False)
    op.create_index('ix_lumen_notices_created_at_index', 'lumen_notices', ['record_created_at'], unique=False)
    op.create_index('ix_lumen_notice_twitter_user_created_at_index', 'lumen_notice_to_twitter_user', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lumen_notice_twitter_user_created_at_index', table_name='lumen_notice_to_twitter_user')
    op.drop_index('ix_lumen_notices_created_at_index', table_name='lumen_notices')
    op.drop_index('ix_twitter_statuses_created_at_index', table_name='twitter_statuses')
    op.drop_index('ix_twitter_users_created_at_index', table_name='twitter_users')
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_twitter_users_created_at_index', 'twitter_users', ['record_created_at'], unique=False)
    op.create_index('ix_twitter_statuses_created_at_index', 'twitter_statuses', ['record_created_at'], unique=False)
    op.create_index('ix_lumen_notices_created_at_index', 'lumen_notices', ['record_created_at'], unique=False)
    op.create_index('ix_lumen_notice_twitter_user_created_at_index', 'lumen_notice_to_twitter_user', ['record_created_at'], unique=False)
    # ### end Alembic commands ###

