"""add subreddit_id field to subreddit_pages

Revision ID: 2957ac0e11b6
Revises: 66a893890997
Create Date: 2016-07-18 17:23:04.904423

"""

# revision identifiers, used by Alembic.
revision = '2957ac0e11b6'
down_revision = '66a893890997'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit_pages', sa.Column('subreddit_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit_pages', 'subreddit_id')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit_pages', sa.Column('subreddit_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit_pages', 'subreddit_id')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddit_pages', sa.Column('subreddit_id', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddit_pages', 'subreddit_id')
    ### end Alembic commands ###

