"""Add comment data to post

Revision ID: 2e09867c0c38
Revises: edffeaf7cd85
Create Date: 2016-07-01 22:27:29.462016

"""

# revision identifiers, used by Alembic.
revision = '2e09867c0c38'
down_revision = 'edffeaf7cd85'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_data', mysql.LONGTEXT(), nullable=True))
    op.add_column('posts', sa.Column('comments_queried_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'comments_queried_at')
    op.drop_column('posts', 'comment_data')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_data', mysql.LONGTEXT(), nullable=True))
    op.add_column('posts', sa.Column('comments_queried_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'comments_queried_at')
    op.drop_column('posts', 'comment_data')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment_data', mysql.LONGTEXT(), nullable=True))
    op.add_column('posts', sa.Column('comments_queried_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'comments_queried_at')
    op.drop_column('posts', 'comment_data')
    ### end Alembic commands ###

