"""Add ModAction model

Revision ID: 4430bb0ac79d
Revises: 2e09867c0c38
Create Date: 2016-07-03 11:05:53.359444

"""

# revision identifiers, used by Alembic.
revision = '4430bb0ac79d'
down_revision = '2e09867c0c38'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_actions',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('mod', sa.String(length=64), nullable=True),
    sa.Column('target_author', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=True),
    sa.Column('target_fullname', sa.String(length=256), nullable=True),
    sa.Column('action_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_mod_actions_subreddit_id'), 'mod_actions', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_mod_actions_target_author'), 'mod_actions', ['target_author'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_actions_target_author'), table_name='mod_actions')
    op.drop_index(op.f('ix_mod_actions_subreddit_id'), table_name='mod_actions')
    op.drop_table('mod_actions')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_actions',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('mod', sa.String(length=64), nullable=True),
    sa.Column('target_author', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=True),
    sa.Column('target_fullname', sa.String(length=256), nullable=True),
    sa.Column('action_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_mod_actions_subreddit_id'), 'mod_actions', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_mod_actions_target_author'), 'mod_actions', ['target_author'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_actions_target_author'), table_name='mod_actions')
    op.drop_index(op.f('ix_mod_actions_subreddit_id'), table_name='mod_actions')
    op.drop_table('mod_actions')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod_actions',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('mod', sa.String(length=64), nullable=True),
    sa.Column('target_author', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=True),
    sa.Column('target_fullname', sa.String(length=256), nullable=True),
    sa.Column('action_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_mod_actions_subreddit_id'), 'mod_actions', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_mod_actions_target_author'), 'mod_actions', ['target_author'], unique=False)
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mod_actions_target_author'), table_name='mod_actions')
    op.drop_index(op.f('ix_mod_actions_subreddit_id'), table_name='mod_actions')
    op.drop_table('mod_actions')
    ### end Alembic commands ###
