"""index on TwitterUser record_created_at

Revision ID: 511fd28e1e06
Revises: 8694114d18e2
Create Date: 2020-06-12 09:23:42.684544

"""

# revision identifiers, used by Alembic.
revision = '511fd28e1e06'
down_revision = '8694114d18e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_users_record_created_at'), 'twitter_users', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_users_record_created_at'), table_name='twitter_users')
    # ### end Alembic commands ###

def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_users_record_created_at'), 'twitter_users', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_users_record_created_at'), table_name='twitter_users')
    # ### end Alembic commands ###

def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_users_record_created_at'), 'twitter_users', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_users_record_created_at'), table_name='twitter_users')
    # ### end Alembic commands ###

