"""twitter tokens autoincrement2

Revision ID: 62632218e063
Revises: 6a0f83ee7d77
Create Date: 2018-07-11 16:48:21.651406

"""

# revision identifiers, used by Alembic.
revision = '62632218e063'
down_revision = '6a0f83ee7d77'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('endpoint', 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_endpoint', 'twitter_ratestate', ['endpoint', 'is_exhausted'], unique=False)
    op.drop_index('endpoint', table_name='twitter_ratestate')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('endpoint', 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_endpoint', 'twitter_ratestate', ['endpoint', 'is_exhausted'], unique=False)
    op.drop_index('endpoint', table_name='twitter_ratestate')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('endpoint', 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_endpoint', 'twitter_ratestate', ['endpoint', 'is_exhausted'], unique=False)
    op.drop_index('endpoint', table_name='twitter_ratestate')
    # ### end Alembic commands ###

