"""twitter tokens autoincrement

Revision ID: 6a0f83ee7d77
Revises: eee2d2e40d5d
Create Date: 2018-07-11 16:46:57.448335

"""

# revision identifiers, used by Alembic.
revision = '6a0f83ee7d77'
down_revision = 'eee2d2e40d5d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_ratestate_is_exhausted'), 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.create_index('user_endpoint', 'twitter_ratestate', ['endpoint', 'is_exhausted'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.create_index('user_endpoint', 'twitter_ratestate', ['user_id', 'endpoint'], unique=False)
    op.drop_index(op.f('ix_twitter_ratestate_is_exhausted'), table_name='twitter_ratestate')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_ratestate_is_exhausted'), 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.create_index('user_endpoint', 'twitter_ratestate', ['endpoint', 'is_exhausted'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.create_index('user_endpoint', 'twitter_ratestate', ['user_id', 'endpoint'], unique=False)
    op.drop_index(op.f('ix_twitter_ratestate_is_exhausted'), table_name='twitter_ratestate')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_ratestate_is_exhausted'), 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.create_index('user_endpoint', 'twitter_ratestate', ['endpoint', 'is_exhausted'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.create_index('user_endpoint', 'twitter_ratestate', ['user_id', 'endpoint'], unique=False)
    op.drop_index(op.f('ix_twitter_ratestate_is_exhausted'), table_name='twitter_ratestate')
    # ### end Alembic commands ###

