"""add user_rand to TwitterUser

Revision ID: 6c462fed1a87
Revises: 0dbd786dc2b3
Create Date: 2018-10-16 08:42:22.745228

"""

# revision identifiers, used by Alembic.
revision = '6c462fed1a87'
down_revision = '0dbd786dc2b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('user_rand', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'user_rand')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('user_rand', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'user_rand')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('user_rand', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'user_rand')
    # ### end Alembic commands ###

