"""create user_metadata table

Revision ID: 7f0c470a4082
Revises: e566e8e209d1
Create Date: 2017-08-03 13:34:34.553191

"""

# revision identifiers, used by Alembic.
revision = '7f0c470a4082'
down_revision = 'e566e8e209d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('field_value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_metadata_field_name'), 'user_metadata', ['field_name'], unique=False)
    op.create_index(op.f('ix_user_metadata_user_id'), 'user_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_metadata_user_id'), table_name='user_metadata')
    op.drop_index(op.f('ix_user_metadata_field_name'), table_name='user_metadata')
    op.drop_table('user_metadata')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('field_value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_metadata_field_name'), 'user_metadata', ['field_name'], unique=False)
    op.create_index(op.f('ix_user_metadata_user_id'), 'user_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_metadata_user_id'), table_name='user_metadata')
    op.drop_index(op.f('ix_user_metadata_field_name'), table_name='user_metadata')
    op.drop_table('user_metadata')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('field_name', sa.String(length=256), nullable=False),
    sa.Column('field_value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_metadata_field_name'), 'user_metadata', ['field_name'], unique=False)
    op.create_index(op.f('ix_user_metadata_user_id'), 'user_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_metadata_user_id'), table_name='user_metadata')
    op.drop_index(op.f('ix_user_metadata_field_name'), table_name='user_metadata')
    op.drop_table('user_metadata')
    # ### end Alembic commands ###

