"""add twitter_status_urls and twitter_tlds

Revision ID: 80bd0e8a9b03
Revises: 17b20129fb86
Create Date: 2019-08-06 17:51:53.330003

"""

# revision identifiers, used by Alembic.
revision = '80bd0e8a9b03'
down_revision = '17b20129fb86'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_merry():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_status_urls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('twitter_status_id', sa.BigInteger(), nullable=True),
    sa.Column('status_data_key', sa.Integer(), nullable=True),
    sa.Column('raw_url', mysql.TEXT(), nullable=True),
    sa.Column('expanded_url', mysql.TEXT(), nullable=True),
    sa.Column('unwound_url', mysql.TEXT(), nullable=True),
    sa.Column('needs_unshorten', sa.Boolean(), nullable=True),
    sa.Column('unshortened_url', mysql.TEXT(), nullable=True),
    sa.Column('error_unshortening', mysql.TINYTEXT(), nullable=True),
    sa.Column('tld_text', mysql.TEXT(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_status_urls_record_created_at'), 'twitter_status_urls', ['record_created_at'], unique=False)
    op.create_index(op.f('ix_twitter_status_urls_twitter_status_id'), 'twitter_status_urls', ['twitter_status_id'], unique=False)
    op.create_table('twitter_tlds',
    sa.Column('id', sa.BigInteger(), nullable=True),
    sa.Column('text', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('is_civic', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_index(op.f('ix_twitter_tlds_id'), 'twitter_tlds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_merry():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_tlds_id'), table_name='twitter_tlds')
    op.drop_table('twitter_tlds')
    op.drop_index(op.f('ix_twitter_status_urls_twitter_status_id'), table_name='twitter_status_urls')
    op.drop_index(op.f('ix_twitter_status_urls_record_created_at'), table_name='twitter_status_urls')
    op.drop_table('twitter_status_urls')
    # ### end Alembic commands ###

