"""add twitteruser column for comparison group

Revision ID: 8694114d18e2
Revises: 80bd0e8a9b03
Create Date: 2020-03-19 16:00:14.187029

"""

# revision identifiers, used by Alembic.
revision = '8694114d18e2'
down_revision = '80bd0e8a9b03'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('created_type', sa.Integer(), nullable=True))
    op.add_column('twitter_users', sa.Column('last_status_dt', sa.DateTime(), nullable=True))
    op.add_column('twitter_users', sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'metadata_json')
    op.drop_column('twitter_users', 'last_status_dt')
    op.drop_column('twitter_users', 'created_type')
    # ### end Alembic commands ###

def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('created_type', sa.Integer(), nullable=True))
    op.add_column('twitter_users', sa.Column('last_status_dt', sa.DateTime(), nullable=True))
    op.add_column('twitter_users', sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'metadata_json')
    op.drop_column('twitter_users', 'last_status_dt')
    op.drop_column('twitter_users', 'created_type')
    # ### end Alembic commands ###

def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('created_type', sa.Integer(), nullable=True))
    op.add_column('twitter_users', sa.Column('last_status_dt', sa.DateTime(), nullable=True))
    op.add_column('twitter_users', sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'metadata_json')
    op.drop_column('twitter_users', 'last_status_dt')
    op.drop_column('twitter_users', 'created_type')
    # ### end Alembic commands ###

