"""Added ix_comments_subreddit_id_created_at index

Revision ID: 879b6b345bd4
Revises: aae7a3158d13
Create Date: 2017-07-27 13:15:32.403889

"""

# revision identifiers, used by Alembic.
revision = '879b6b345bd4'
down_revision = 'aae7a3158d13'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_subreddit_id_created_at', 'comments', ['subreddit_id', 'created_at'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_subreddit_id_created_at', table_name='comments')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comments_subreddit_id_created_at', 'comments', ['subreddit_id', 'created_at'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_subreddit_id_created_at', table_name='comments')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    ## COMMENTED OUT BECAUSE THIS WAS ADDED MANUALLY ON PRODUCTION.
    ## YOU WILL NEED TO UNCOMMENT THIS IF YOU ARE SETTING UP A NEW PRODUCTION ENVIRONMENT
    #op.create_index('ix_comments_subreddit_id_created_at', 'comments', ['subreddit_id', 'created_at'], unique=False)
    ### end Alembic commands ###
    pass


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_subreddit_id_created_at', table_name='comments')
    ### end Alembic commands ###

