"""change subreddit, page ids to varchars

Revision ID: 91d1f38830f1
Revises: e9a1dbe2ff2a
Create Date: 2016-06-10 13:19:48.824177

"""

# revision identifiers, used by Alembic.
revision = '91d1f38830f1'
down_revision = 'e9a1dbe2ff2a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    pass


def downgrade_development():
    pass


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_production():
    pass


def downgrade_production():
    pass

