"""added message log

Revision ID: a0cca001e8a7
Revises: df498825ec28
Create Date: 2018-04-21 12:04:18.535978

"""

# revision identifiers, used by Alembic.
revision = 'a0cca001e8a7'
down_revision = 'df498825ec28'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message_sent', sa.Boolean(), nullable=True),
    sa.Column('message_failure_reason', sa.String(length=63), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('message_task_id', sa.String(length=256), nullable=True),
    sa.Column('body', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_created_at'), 'message_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_logs_message_task_id'), 'message_logs', ['message_task_id'], unique=False)
    op.create_index(op.f('ix_message_logs_platform'), 'message_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_message_logs_username'), 'message_logs', ['username'], unique=False)
    op.drop_index('ix_mod_actions_created_utc_index', table_name='mod_actions')
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mod_actions_created_utc_index', 'mod_actions', ['created_utc'], unique=False)
    op.drop_index(op.f('ix_message_logs_username'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_platform'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_message_task_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_created_at'), table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message_sent', sa.Boolean(), nullable=True),
    sa.Column('message_failure_reason', sa.String(length=63), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('message_task_id', sa.String(length=256), nullable=True),
    sa.Column('body', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_created_at'), 'message_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_logs_message_task_id'), 'message_logs', ['message_task_id'], unique=False)
    op.create_index(op.f('ix_message_logs_platform'), 'message_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_message_logs_username'), 'message_logs', ['username'], unique=False)
    op.drop_index('ix_mod_actions_created_utc_index', table_name='mod_actions')
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mod_actions_created_utc_index', 'mod_actions', ['created_utc'], unique=False)
    op.drop_index(op.f('ix_message_logs_username'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_platform'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_message_task_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_created_at'), table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('message_sent', sa.Boolean(), nullable=True),
    sa.Column('message_failure_reason', sa.String(length=63), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('message_task_id', sa.String(length=256), nullable=True),
    sa.Column('body', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_created_at'), 'message_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_logs_message_task_id'), 'message_logs', ['message_task_id'], unique=False)
    op.create_index(op.f('ix_message_logs_platform'), 'message_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_message_logs_username'), 'message_logs', ['username'], unique=False)
    op.create_index('ix_comments_subreddit_id_created_at', 'comments', ['subreddit_id', 'created_at'], unique=False)
    op.drop_index('ix_mod_actions_created_utc_index', table_name='mod_actions')
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mod_actions_created_utc_index', 'mod_actions', ['created_utc'], unique=False)
    op.drop_index('ix_comments_subreddit_id_created_at', table_name='comments')
    op.drop_index(op.f('ix_message_logs_username'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_platform'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_message_task_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_created_at'), table_name='message_logs')
    op.drop_table('message_logs')
    # ### end Alembic commands ###

