"""Add model for snapshots of ExperimentThings

Revision ID: a0f4fda7588f
Revises: ae72c799d321
Create Date: 2016-11-26 22:05:26.728790

"""

# revision identifiers, used by Alembic.
revision = 'a0f4fda7588f'
down_revision = 'ae72c799d321'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_thing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_thing_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('object_type', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_thing_snapshots_experiment_id'), 'experiment_thing_snapshots', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_thing_snapshots_experiment_thing_id'), 'experiment_thing_snapshots', ['experiment_thing_id'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_thing_snapshots_experiment_thing_id'), table_name='experiment_thing_snapshots')
    op.drop_index(op.f('ix_experiment_thing_snapshots_experiment_id'), table_name='experiment_thing_snapshots')
    op.drop_table('experiment_thing_snapshots')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_thing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_thing_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('object_type', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_thing_snapshots_experiment_id'), 'experiment_thing_snapshots', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_thing_snapshots_experiment_thing_id'), 'experiment_thing_snapshots', ['experiment_thing_id'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_thing_snapshots_experiment_thing_id'), table_name='experiment_thing_snapshots')
    op.drop_index(op.f('ix_experiment_thing_snapshots_experiment_id'), table_name='experiment_thing_snapshots')
    op.drop_table('experiment_thing_snapshots')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_thing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_thing_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('object_type', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_thing_snapshots_experiment_id'), 'experiment_thing_snapshots', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_thing_snapshots_experiment_thing_id'), 'experiment_thing_snapshots', ['experiment_thing_id'], unique=False)
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_thing_snapshots_experiment_thing_id'), table_name='experiment_thing_snapshots')
    op.drop_index(op.f('ix_experiment_thing_snapshots_experiment_id'), table_name='experiment_thing_snapshots')
    op.drop_table('experiment_thing_snapshots')
    ### end Alembic commands ###

