"""create eventhook table

Revision ID: a571e57d884a
Revises: 16dbded8a5cf
Create Date: 2017-06-18 19:48:18.987660

"""

# revision identifiers, used by Alembic.
revision = 'a571e57d884a'
down_revision = '16dbded8a5cf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('call_when', sa.Integer(), nullable=True),
    sa.Column('caller_controller', sa.String(length=256), nullable=False),
    sa.Column('caller_method', sa.String(length=256), nullable=False),
    sa.Column('callee_module', sa.String(length=256), nullable=False),
    sa.Column('callee_controller', sa.String(length=256), nullable=False),
    sa.Column('callee_method', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_hooks_experiment_id'), 'event_hooks', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_event_hooks_name'), 'event_hooks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_hooks_name'), table_name='event_hooks')
    op.drop_index(op.f('ix_event_hooks_experiment_id'), table_name='event_hooks')
    op.drop_table('event_hooks')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('call_when', sa.Integer(), nullable=True),
    sa.Column('caller_controller', sa.String(length=256), nullable=False),
    sa.Column('caller_method', sa.String(length=256), nullable=False),
    sa.Column('callee_module', sa.String(length=256), nullable=False),
    sa.Column('callee_controller', sa.String(length=256), nullable=False),
    sa.Column('callee_method', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_hooks_experiment_id'), 'event_hooks', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_event_hooks_name'), 'event_hooks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_hooks_name'), table_name='event_hooks')
    op.drop_index(op.f('ix_event_hooks_experiment_id'), table_name='event_hooks')
    op.drop_table('event_hooks')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('call_when', sa.Integer(), nullable=True),
    sa.Column('caller_controller', sa.String(length=256), nullable=False),
    sa.Column('caller_method', sa.String(length=256), nullable=False),
    sa.Column('callee_module', sa.String(length=256), nullable=False),
    sa.Column('callee_controller', sa.String(length=256), nullable=False),
    sa.Column('callee_method', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_hooks_experiment_id'), 'event_hooks', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_event_hooks_name'), 'event_hooks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_hooks_name'), table_name='event_hooks')
    op.drop_index(op.f('ix_event_hooks_experiment_id'), table_name='event_hooks')
    op.drop_table('event_hooks')
    # ### end Alembic commands ###

