"""Added comment archive table, to split production from archive

Revision ID: aae7a3158d13
Revises: 2959fa8d7ad8
Create Date: 2017-07-26 21:49:44.733366

"""

# revision identifiers, used by Alembic.
revision = 'aae7a3158d13'
down_revision = '2959fa8d7ad8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_comments',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('comment_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_archived_comments_created_at'), 'archived_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_archived_comments_post_id'), 'archived_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_archived_comments_subreddit_id'), 'archived_comments', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_archived_comments_user_id'), 'archived_comments', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_comments_user_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_subreddit_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_post_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_created_at'), table_name='archived_comments')
    op.drop_table('archived_comments')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_comments',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('comment_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_archived_comments_created_at'), 'archived_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_archived_comments_post_id'), 'archived_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_archived_comments_subreddit_id'), 'archived_comments', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_archived_comments_user_id'), 'archived_comments', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_comments_user_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_subreddit_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_post_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_created_at'), table_name='archived_comments')
    op.drop_table('archived_comments')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_comments',
    sa.Column('id', sa.String(length=256), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=True),
    sa.Column('subreddit_id', sa.String(length=32), nullable=True),
    sa.Column('post_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('comment_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_archived_comments_created_at'), 'archived_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_archived_comments_post_id'), 'archived_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_archived_comments_subreddit_id'), 'archived_comments', ['subreddit_id'], unique=False)
    op.create_index(op.f('ix_archived_comments_user_id'), 'archived_comments', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_comments_user_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_subreddit_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_post_id'), table_name='archived_comments')
    op.drop_index(op.f('ix_archived_comments_created_at'), table_name='archived_comments')
    op.drop_table('archived_comments')
    ### end Alembic commands ###

