"""create fills table

Revision ID: cd494c3a75aa
Revises: 6c462fed1a87
Create Date: 2019-01-02 15:47:38.340181

"""

# revision identifiers, used by Alembic.
revision = 'cd494c3a75aa'
down_revision = '6c462fed1a87'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_fills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.Column('fill_type', mysql.TINYTEXT(), nullable=True),
    sa.Column('fill_start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_fills_record_created_at'), 'twitter_fills', ['record_created_at'], unique=False)
    op.create_index(op.f('ix_twitter_fills_user_id'), 'twitter_fills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_fills_user_id'), table_name='twitter_fills')
    op.drop_index(op.f('ix_twitter_fills_record_created_at'), table_name='twitter_fills')
    op.drop_table('twitter_fills')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_fills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.Column('fill_type', mysql.TINYTEXT(), nullable=True),
    sa.Column('fill_start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_fills_record_created_at'), 'twitter_fills', ['record_created_at'], unique=False)
    op.create_index(op.f('ix_twitter_fills_user_id'), 'twitter_fills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_fills_user_id'), table_name='twitter_fills')
    op.drop_index(op.f('ix_twitter_fills_record_created_at'), table_name='twitter_fills')
    op.drop_table('twitter_fills')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_fills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('record_created_at', sa.DateTime(), nullable=True),
    sa.Column('fill_type', mysql.TINYTEXT(), nullable=True),
    sa.Column('fill_start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_fills_record_created_at'), 'twitter_fills', ['record_created_at'], unique=False)
    op.create_index(op.f('ix_twitter_fills_user_id'), 'twitter_fills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_fills_user_id'), table_name='twitter_fills')
    op.drop_index(op.f('ix_twitter_fills_record_created_at'), table_name='twitter_fills')
    op.drop_table('twitter_fills')
    # ### end Alembic commands ###

