"""add index to twitterstatus record_created_at

Revision ID: dd20ee8bb3d3
Revises: 4a4bfc2ce8f5
Create Date: 2018-08-28 09:31:17.028282

"""

# revision identifiers, used by Alembic.
revision = 'dd20ee8bb3d3'
down_revision = '4a4bfc2ce8f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_record_created_at'), 'twitter_statuses', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_record_created_at'), table_name='twitter_statuses')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_record_created_at'), 'twitter_statuses', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_record_created_at'), table_name='twitter_statuses')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_twitter_statuses_record_created_at'), 'twitter_statuses', ['record_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_statuses_record_created_at'), table_name='twitter_statuses')
    # ### end Alembic commands ###

