"""Added query_index to ExperimentThing

Revision ID: e566e8e209d1
Revises: 879b6b345bd4
Create Date: 2017-07-29 19:57:15.738850

"""

# revision identifiers, used by Alembic.
revision = 'e566e8e209d1'
down_revision = '879b6b345bd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_things', sa.Column('query_index', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_experiment_things_object_created'), 'experiment_things', ['object_created'], unique=False)
    op.create_index(op.f('ix_experiment_things_query_index'), 'experiment_things', ['query_index'], unique=False)
    ### end Alembic commands ###


def downgrade_development():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_things_query_index'), table_name='experiment_things')
    op.drop_index(op.f('ix_experiment_things_object_created'), table_name='experiment_things')
    op.drop_column('experiment_things', 'query_index')
    ### end Alembic commands ###


def upgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_things', sa.Column('query_index', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_experiment_things_object_created'), 'experiment_things', ['object_created'], unique=False)
    op.create_index(op.f('ix_experiment_things_query_index'), 'experiment_things', ['query_index'], unique=False)
    ### end Alembic commands ###


def downgrade_test():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_things_query_index'), table_name='experiment_things')
    op.drop_index(op.f('ix_experiment_things_object_created'), table_name='experiment_things')
    op.drop_column('experiment_things', 'query_index')
    ### end Alembic commands ###


def upgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_things', sa.Column('query_index', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_experiment_things_object_created'), 'experiment_things', ['object_created'], unique=False)
    op.create_index(op.f('ix_experiment_things_query_index'), 'experiment_things', ['query_index'], unique=False)
    ### end Alembic commands ###


def downgrade_production():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_things_query_index'), table_name='experiment_things')
    op.drop_index(op.f('ix_experiment_things_object_created'), table_name='experiment_things')
    op.drop_column('experiment_things', 'query_index')
    ### end Alembic commands ###

