"""empty message

Revision ID: ebc68b1d529f
Revises: 651c00637cc4
Create Date: 2018-08-21 10:45:47.518452

"""

# revision identifiers, used by Alembic.
revision = 'ebc68b1d529f'
down_revision = '651c00637cc4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_users', sa.Column('last_attempted_process', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_users', 'last_attempted_process')
    # ### end Alembic commands ###


def upgrade_test():
    pass


def downgrade_test():
    pass


def upgrade_production():
    pass


def downgrade_production():
    pass

