"""twitter usertokens

Revision ID: eee2d2e40d5d
Revises: 200471c7e77d
Create Date: 2018-07-08 14:55:40.671940

"""

# revision identifiers, used by Alembic.
revision = 'eee2d2e40d5d'
down_revision = '200471c7e77d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_ratestate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('is_exhausted', sa.Boolean(), nullable=True),
    sa.Column('checkin_due', sa.DateTime(), nullable=True),
    sa.Column('reset_time', sa.DateTime(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('resources', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_ratestate_endpoint'), 'twitter_ratestate', ['endpoint'], unique=False)
    op.create_index(op.f('ix_twitter_ratestate_user_id'), 'twitter_ratestate', ['user_id'], unique=False)
    op.create_index('user_endpoint', 'twitter_ratestate', ['user_id', 'endpoint'], unique=False)
    op.create_table('twitter_tokens',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('oauth_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade_development():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_tokens')
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.drop_index(op.f('ix_twitter_ratestate_user_id'), table_name='twitter_ratestate')
    op.drop_index(op.f('ix_twitter_ratestate_endpoint'), table_name='twitter_ratestate')
    op.drop_table('twitter_ratestate')
    # ### end Alembic commands ###


def upgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_ratestate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('is_exhausted', sa.Boolean(), nullable=True),
    sa.Column('checkin_due', sa.DateTime(), nullable=True),
    sa.Column('reset_time', sa.DateTime(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('resources', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_ratestate_endpoint'), 'twitter_ratestate', ['endpoint'], unique=False)
    op.create_index(op.f('ix_twitter_ratestate_user_id'), 'twitter_ratestate', ['user_id'], unique=False)
    op.create_index('user_endpoint', 'twitter_ratestate', ['user_id', 'endpoint'], unique=False)
    op.create_table('twitter_tokens',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('oauth_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade_test():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_tokens')
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.drop_index(op.f('ix_twitter_ratestate_user_id'), table_name='twitter_ratestate')
    op.drop_index(op.f('ix_twitter_ratestate_endpoint'), table_name='twitter_ratestate')
    op.drop_table('twitter_ratestate')
    # ### end Alembic commands ###


def upgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_ratestate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.String(length=64), nullable=True),
    sa.Column('is_exhausted', sa.Boolean(), nullable=True),
    sa.Column('checkin_due', sa.DateTime(), nullable=True),
    sa.Column('reset_time', sa.DateTime(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('resources', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_ratestate_endpoint'), 'twitter_ratestate', ['endpoint'], unique=False)
    op.create_index(op.f('ix_twitter_ratestate_user_id'), 'twitter_ratestate', ['user_id'], unique=False)
    op.create_index('user_endpoint', 'twitter_ratestate', ['user_id', 'endpoint'], unique=False)
    op.create_table('twitter_tokens',
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('oauth_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade_production():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter_tokens')
    op.drop_index('user_endpoint', table_name='twitter_ratestate')
    op.drop_index(op.f('ix_twitter_ratestate_user_id'), table_name='twitter_ratestate')
    op.drop_index(op.f('ix_twitter_ratestate_endpoint'), table_name='twitter_ratestate')
    op.drop_table('twitter_ratestate')
    # ### end Alembic commands ###

